### ISSUE TITLE
Give Credit to Kris

### ISSUE THREAD

**Issue by jrsmiley** [simondlevy/EM7180#1]
You should really give more credit to Kris.  Much of your code is a line-for-line copy of his code.  

There's another github library for the EM7180 based on Kris' code that comes right out and says so:
https://github.com/andrewadare

**Comment by simondlevy** [comment]
Dang, I thought I already had an acknowledgment/link to Kris's repo in my README, but I must've forgotten to commit it.  Fixed now, so thanks for pointing out the faux pas.  I'm hoping to add more functionality and clean up the examples to make it less like a copy-paste job.
