### ISSUE TITLE
Port to work with MicroPython

### ISSUE THREAD

**Issue by JonHylands** [simondlevy/EM7180#12]
Hi Simon, opening an issue as requested to ask for a MicroPython port.

I'll copy the info I emailed you here:

line 21:
from pyb import I2C

line 118:
self.bus = I2C(bus, I2C.MASTER)

line 528
self.bus.mem_write(data, self.ADDRESS, subAddress)

remove line 530
line 532:
return self.bus.mem_read(count, self.ADDRESS, subAddress)

Thanks!

**Comment by simondlevy** [comment]
Thanks for doing this, Jon.  I've committed a new version, which should work automatically with both platforms (MicroPython and RaspberryPi).  I haven't been able to test it, however.  So if you can pull the new code and try it out on your board, I can close the issue and give you credit for this nice new capability.  Also, please let me know which specific microcontroller board you're using, so I can mention it in this list of platforms on which the library has been tested.

**Comment by JonHylands** [comment]
Hi Simon, I just uploaded the code onto my official Pyboard, and it works just fine. I have a PYBv1.0 (which was the original kickstarter reward way back when it first started).

http://docs.micropython.org/en/latest/pyboard/quickref.html

**Comment by simondlevy** [comment]
Thanks again for your work on this, Jon.  I've added the PYBv1.0 to the list of supported boards, crediting you for the work, and I've sent you a collaborator invite in case you want to add a sentence or two to the README with tips on how to run it.
