### ISSUE TITLE
raspberry M24512DFMwriteBytes and M24512DFMreadBytes

### ISSUE THREAD

**Issue by samuelgirardin** [simondlevy/EM7180#14]
Hello Simon, 

I'm working on  a raspberry pi EM7180 /LSM6 GUI, based on your code EM7180/wiringPI.
The best way for me to try to understand how all of this work. 
I can't achieve to write accelerometer calibration data to the EEPROM. So I'm wondering if there is a  a way with wiringpi to have something similar to this method : 

`static void M24512DFMwriteBytes(uint8_t device_address, uint8_t data_address1, uint8_t data_address2, uint8_t count, uint8_t * dest)`  and ` M24512DFMreadBytes(...)` 

 (found in WarmStartAccCal.ino) working with wiringpi ? Maybe you can pointed me out something I missed. I'm not really familiar with this kind of dev. Anyway thanks a lot for all your dev about PI/EM7180. It helped me a lot.  
[EM7180 png gui preview](http://www.visualiser.fr/img/sentral.png). 
sam.

**Comment by samuelgirardin** [comment]
Found, I use  <linux/i2c-dev.h> lib  to read and write to the M24512.

**Comment by LaurentDelaon** [comment]
Hi samuel,

I have the same pb.
I want to calibrate em7180 on tx2...
How did you do it  ?
Could you send me your code please ?
thank's.
Laurent.
