### ISSUE TITLE
compile error in FullTest.ino, include <stdint.h> in EM7180.h to fix

### ISSUE THREAD

**Issue by aksell** [simondlevy/EM7180#3]
# Error when compiling
After cloning the repo in to my sketchbook/lib i tried compiling [FullTest.ino](https://github.com/simondlevy/EM7180/blob/master/examples/FullTest/FullTest.ino) in the arduino IDE. I got the error "/sketchbook/libraries/EM7180/EM7180.h:28:32: error: `uint8_t` has not been declared static bool hasFeature(uint8_t features);" . 

# Fix
To fix the problem i had to put 
```
#include <stdint.h>
```
In EM7180.h

**Comment by simondlevy** [comment]
Thanks, askell. I've added this fix.
